### ISSUE TITLE
Make library assets more accessible

### ISSUE THREAD

**Issue by marian-r** [aol/aol-hb.js#8]
I would suggest the following improvements:

- [x] create [prepublish](https://docs.npmjs.com/misc/scripts#common-uses) npm script to create precompiled files
- [x] publish the package on npm
- [x] create a [release on GitHub](https://github.com/aol/aol-hb.js/releases) with precompiled assets
- [x] update README accordingly

For publishing I recommend using [np](https://github.com/sindresorhus/np) and bump from 0.0.0.

**Comment by vzhukovsky** [comment]
Done.
